### PR TITLE
Draft: 46: Challenge required

### PR DESCRIPTION
**Pull request by stanvanrooy**
- [x] Handle basic challenges ("New login detected. Was this you?")
- [ ] Handle phone verification code challenges
- [ ] Handle email verification code challenges

### CODE REVIEW

**Comment by marvic2409** [comment]
What is your plan for handling phone and email verification codes?

**Comment by stanvanrooy** [comment]
I need the request headers & bodies that are being sent when the challenge is done. Without those, I can't do much.

I haven't been able to figure out how to trigger such a challenge manually.

**Comment by marvic2409** [comment]
I accidentally triggered it when I accessed my account from multiple ips, maybe that could work?

**Comment by stanvanrooy** [comment]
I tried that but only got the simple "Was this you?" challenges.

**Comment by marvic2409** [comment]
I've been trying to trigger a challenge (Including connecting from a vpn, from tor, and from different devices) and so far haven't gotten one. I'll keep using my account as normal and if I get any challenges I'll make sure to send you the headers/data

**Comment by stanvanrooy** [comment]
SG. The code verifications only really happen when they detect spam behaviour from the account.

**Comment by marvic2409** [comment]
Lol I guess uploading 87 of the same image from like 10 different ips doesn't count as spam. Their flagging system is pretty weird

**Pull request merged**
