### PR TITLE
Changed init arguments to expect an `ApiClient` instance

### PR DESCRIPTION
**Pull request by tibotix**
Now someone can pass easily an already logged in `ApiClient` instance to the Bot.
For credential login `from_credentials` classmethod was added.

### CODE REVIEW

**Comment by stanvanrooy** [comment]
Could you fix the merge conflicts?

**Comment by tibotix** [comment]
Okay, done

**Comment by stanvanrooy** [comment]
Lgtm. 1 small thing, could you switch the credentials back to `__init__`, and instead create a classmethod `from_client`?

**Comment by tibotix** [comment]
Okay, i think that's it. `__init__` arguments can now also takes a client instance as optional parameter so the Bot can simply use it.

Alternatively we could save the `ApiClient` in `from_client` to file and let the `__init__` method initialize the `Bot` instance from the same file. But i think first solution is the more cleaner way.

**Comment by tibotix** [comment]
Can it be merged?

**Comment by stanvanrooy** [comment]
Let's not mix the responsibilities of the methods. The way you had it before was perfect, with the `from_client` class method.

**Comment by tibotix** [comment]
Okay. But if we have only `username` and `password` in the `__init__` function as parameters, the `from_client` method would have no chance to initialize without passing `username` and `password`.
It would be easier to switch responsibilities by creating `from_credentials` classmethod which will create the `ApiClient` and pass it to `__init__` which will only expect one `ApiClient` instance.
The way I have it now will work as well too.

**Comment by stanvanrooy** [comment]
If you want to re-authenticate the `ApiClient`, and use the `from_client` method, you should initiate the `ApiClient` itself with a username & pass itself, and handle login from there.

That's out of scope for the `Bot` class.

**Comment by tibotix** [comment]
Okay, I don't know if I understood that correctly. My use case that I am thought about was:

```
# initiate ApiClient and log into the account
client = ApiClient(user_name=username, password=password)
client.login()

# use client 
instauto.helpers.post.retrieve_posts_from_user(client, 2, username="instagram")
# ....
# ....

# now use the Bot class. I don't want to re log in cause I already have a usable client. 
# the way it would work after merging:
bot = Bot.from_client(client)
# someone can also initiate directly with credentials
bot = Bot(user_name=username, password=password)


# workaround that just works(not so clean i think):
client.save_to_disk(f'.{username}.instauto.save')
bot = Bot(user_name=username)
```

The `Bot` just authenticated by internally initiating the `ApiClient` either from credentials or from a file.
I think it would be cleaner to give the ability to pass a *ready-to-use* `ApiClient` to the `Bot` instance and of course also preserve the ability to initiate the `Bot` only from credentials so that you don't have to care about initiating `ApiClient` by yourself.

**Comment by stanvanrooy** [comment]
I misread your comments. Looks good. Could you change `if(isinstance(client, ApiClient)):`, to `if client is not None`.

The pr is ready to merge after that.

**Comment by tibotix** [comment]
Perfect. Thanks :-)

**Comment by stanvanrooy** [comment]
@all-contributors please add @tibotix for code

**Pull request merged**
