### PR TITLE
fixed documentation link

### PR DESCRIPTION
**Pull request by javad94**

### CODE REVIEW

**Comment by stanvanrooy** [comment]
Thanks! 

@all-contributors, please add @javad94 for documentation

**Comment by javad94** [comment]
> Thanks!
> 
> @all-contributors, please add @javad94 for documentation

you're very welcome. Thanks for this great library/

**Comment by stanvanrooy** [comment]
@all-contributors please add @javad94 for code

**Comment by stanvanrooy** [comment]
@allcontributors please add @javad94 for documentation

**Comment by stanvanrooy** [comment]
Third time's a charm :)

**Comment by stanvanrooy** [comment]
@allcontributors please add @javad94 for docs

**Pull request merged**
